[package]
name = "auto-mando"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Vincent Tam <https://github.com/VincentTam>"]
license = "MIT"
description = "Automatic conversion to Mandarin romanizations from Chinese characters."
repository = "https://github.com/VincentTam/auto-mando"
keywords = [
    "Mandarin",
    "pinyin",
    "Chinese",
    "conversion",
]
categories = [
    "text",
    "languages",
    "utility",
]
disciplines = [
    "education",
    "linguistics",
]
compiler = "0.14.0"
exclude = ["example.png"]

[tool]
